### KPoEM 데이터셋 불러오기

In [1]:
!pip install plotly
!pip install -U nbformat

Requirement already satisfied: plotly in /Users/irolim/Documents/한중연/4차시/학위논문/플랫폼/KPoEM Interface/venv/lib/python3.12/site-packages (6.7.0)
Requirement already satisfied: narwhals>=1.15.1 in /Users/irolim/Documents/한중연/4차시/학위논문/플랫폼/KPoEM Interface/venv/lib/python3.12/site-packages (from plotly) (2.22.0)
Requirement already satisfied: packaging in /Users/irolim/Documents/한중연/4차시/학위논문/플랫폼/KPoEM Interface/venv/lib/python3.12/site-packages (from plotly) (25.0)

[notice] A new release of pip is available: 24.2 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: nbformat in /Users/irolim/Documents/한중연/4차시/학위논문/플랫폼/KPoEM Interface/venv/lib/python3.12/site-packages (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in /Users/irolim/Documents/한중연/4차시/학위논문/플랫폼/KPoEM Interface/venv/lib/python3.12/site-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /Users/irolim/Documents/한중연/4차시/학위논문/플랫폼/KPoEM Interface/venv/lib/python3.12/site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /Users/irolim/Documents/한중연/4차시/학위논문/플랫폼/KPoEM Interface/venv/lib/python3.12/site-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /Users/irolim/Documents/한중연/4차시/학위논문/플랫폼/KPoEM Interface/venv/lib/python3.12/site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in /Users/irolim/Documents/한중연/4차시/학위논문/플랫폼/KPoEM Interface/venv/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Users/irolim/Documents/한중연/4차시/학위논문/플랫폼/KPoEM Interface/venv/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /Users/irolim/Documents/한중연/4차시/학위논문/플랫폼/KPoEM Interface/venv/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /Users/irolim/Documents/한중연/4차시/학위논문/플랫폼/KPoEM Interface/venv/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat) (2026.5.1)
Requirement already satisfied: platformdirs>=2.5 in /Users/irolim/Documents/한중연/4차시/학위논문/플랫폼/KPoEM Interface/venv/lib/python3.12/site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.5.1)
Requirement already satisfied: typing-extensions>=4.4.0 in /Users/irolim/Documents/한중연/4차시/학위논문/플랫폼/KPoEM Interface/venv/lib/python3.12/site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat) (4.15.0)

[notice] A new release of pip is available: 24.2 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

### KPoEM 주석자 분석 (python 3.12.3)

In [2]:
import os
import requests
import pandas as pd
import plotly.express as px
from datasets import load_dataset

/Users/irolim/Documents/한중연/4차시/학위논문/플랫폼/KPoEM Interface/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
# KPoEM 데이터셋(작품 단위) 로드
poem_df_ = load_dataset(
    "csv",  # csv 포맷으로 읽기
    data_files={
        "train": "hf://datasets/AKS-DHLAB/KPoEM/KPoEM_poem_dataset_v4.tsv",  # Hugging Face에 저장된 TSV 파일 경로
    },
    delimiter="\t",  # TSV 파일이므로 탭 구분자 지정
    encoding="utf-8",  # UTF-8 인코딩 (필요 시 "utf-8-sig" 사용)
    quoting=3,        # csv.QUOTE_NONE → 인용부호 무시
)

# HuggingFace Dataset → Pandas DataFrame 변환
poem_df = poem_df_["train"].to_pandas()

# 데이터 확인 (상위 5행 미리보기)
poem_df.head()

,seg_id,poem_id,text,sub_title,title,poetry_book,poet,annotator_01,annotator_02,annotator_03,annotator_04,annotator_05
0,1,1,"죽는 날까지 하늘을 우러러 한 점 부끄럼이 없기를, 잎새에 이는 바람에도 나는 괴로...",None,서시,하늘과 바람과 별과 시,윤동주,"불안/걱정, 비장함, 서러움, 슬픔, 안타까움/실망, 부끄러움, 죄책감, 패배/자기혐오","패배/자기혐오, 서러움, 비장함, 부끄러움, 아껴주는, 슬픔, 불안/걱정, 죄책감","깨달음, 흐뭇함(귀여움/예쁨), 고마움, 힘듦/지침, 안타까움/실망","비장함, 뿌듯함, 슬픔","비장함, 감동/감탄, 깨달음, 서러움"
1,2,2,산모퉁이를 돌아 논가 외딴 우물을 홀로 찾아가선 가만히 들여다봅니다. 우물 속에는 ...,None,자화상,하늘과 바람과 별과 시,윤동주,"불쌍함/연민, 아껴주는, 신기함/관심, 흐뭇함(귀여움/예쁨), 서러움, 짜증, 지긋...","신기함/관심, 증오/혐오, 불쌍함/연민, 화남/분노, 서러움, 슬픔, 아껴주는, 패...","안타까움/실망, 서러움, 슬픔, 깨달음, 흐뭇함(귀여움/예쁨)","불평/불만, 안타까움/실망, 의심/불신, 슬픔","불쌍함/연민, 불안/걱정"
2,3,3,쫓아오든 햇빛인데 지금 교회당 꼭대기 십자가에 걸리었습니다. 첨탑(尖塔)이 저렇게...,None,십자가,하늘과 바람과 별과 시,윤동주,"서러움, 패배/자기혐오, 존경, 감동/감탄, 비장함, 불쌍함/연민, 불안/걱정, 죄책감","감동/감탄, 놀람, 불쌍함/연민, 비장함, 슬픔, 행복, 아껴주는, 불안/걱정","절망, 깨달음, 서러움, 힘듦/지침, 존경, 비장함","당황/난처, 힘듦/지침, 놀람, 슬픔, 불안/걱정","깨달음, 비장함, 존경, 신기함/관심"
3,4,4,바람이 어디로부터 불어 와 어디로 불려 가는 것일까 바람이 부는데 내 괴로움에는 ...,None,바람이 불어,하늘과 바람과 별과 시,윤동주,"슬픔, 서러움, 한심함, 패배/자기혐오, 죄책감, 부끄러움","비장함, 서러움, 슬픔, 불안/걱정, 패배/자기혐오, 죄책감","힘듦/지침, 안타까움/실망, 서러움, 절망, 깨달음","힘듦/지침, 당황/난처, 불안/걱정, 불평/불만, 슬픔, 부끄러움, 패배/자기혐오","깨달음, 불쌍함/연민, 불안/걱정, 서러움, 패배/자기혐오, 힘듦/지침"
4,5,5,고향에 돌아온 날 밤에 내 백골(白骨)이 따라와 한방에 누웠다. 어둔 방은 우주로...,None,또 다른 고향,하늘과 바람과 별과 시,윤동주,"불쌍함/연민, 비장함, 공포/무서움, 슬픔, 서러움, 의심/불신, 깨달음, 기대감","힘듦/지침, 놀람, 서러움, 슬픔, 감동/감탄, 존경, 죄책감, 패배/자기혐오, 비...","절망, 깨달음, 서러움, 힘듦/지침, 안타까움/실망","슬픔, 힘듦/지침, 절망, 기대감, 안타까움/실망, 불안/걱정","공포/무서움, 당황/난처, 놀람, 불안/걱정, 비장함"

In [4]:
# KPoEM 데이터셋(행/시구 단위) 로드
line_df_ = load_dataset(
    "csv",  # CSV 포맷으로 읽기
    data_files={
        "train": "hf://datasets/AKS-DHLAB/KPoEM/KPoEM_line_dataset_v4.tsv",  # Hugging Face에 저장된 시구 단위 데이터 경로
    },
    delimiter="\t",  # 탭 구분자 지정
    encoding="utf-8",  # UTF-8 인코딩 (필요 시 "utf-8-sig" 사용 가능)
    quoting=3,        # csv.QUOTE_NONE → 인용부호 무시
)

# HuggingFace Dataset → Pandas DataFrame 변환
line_df = line_df_["train"].to_pandas()

# 데이터 확인 (상위 5행 미리보기)
line_df.head()

,line_id,poem_id,text,sub_title,title,poet,annotator_01,annotator_02,annotator_03,annotator_04,annotator_05
0,1,1,죽는 날까지 하늘을 우러러,None,서시,윤동주,비장함,비장함,"뿌듯함, 비장함","비장함, 뿌듯함, 감동/감탄","비장함, 서러움, 슬픔"
1,2,1,"한 점 부끄럼이 없기를,",None,서시,윤동주,"부끄러움, 비장함","부끄러움, 비장함, 기대감, 불안/걱정, 서러움, 슬픔","깨달음, 비장함, 뿌듯함","비장함, 부끄러움, 기대감",비장함
2,3,1,잎새에 이는 바람에도,None,서시,윤동주,"기대감, 신기함/관심","기대감, 불안/걱정, 비장함","슬픔, 서러움, 불안/걱정, 당황/난처","비장함, 슬픔","감동/감탄, 신기함/관심, 편안/쾌적, 기대감"
3,4,1,나는 괴로워했다.,None,서시,윤동주,"절망, 슬픔, 패배/자기혐오","절망, 슬픔, 패배/자기혐오, 죄책감, 힘듦/지침, 비장함","당황/난처, 서러움, 죄책감, 패배/자기혐오","비장함, 슬픔, 패배/자기혐오, 절망, 힘듦/지침","슬픔, 서러움, 절망, 힘듦/지침, 패배/자기혐오"
4,5,1,별을 노래하는 마음으로,None,서시,윤동주,"기쁨, 신기함/관심, 즐거움/신남, 흐뭇함(귀여움/예쁨), 뿌듯함","기쁨, 뿌듯함, 감동/감탄, 슬픔, 비장함, 아껴주는, 환영/호의, 기대감","고마움, 기대감, 기쁨, 아껴주는, 흐뭇함(귀여움/예쁨)","감동/감탄, 기대감, 기쁨, 아껴주는, 행복","즐거움/신남, 기대감, 기쁨, 행복"

In [5]:
# 행 데이터셋 + 작품 데이터셋 정리
# 주석자 결측치 점검 - 데이터 개수가 유지되므로, 결측치 없음. (total 데이터 개수: 7622행)
# lineID, poemSegID 열 제거
# 불필요한 열 제거 후, 1부터 indexing

df_combined = pd.concat([line_df, poem_df], ignore_index=True, sort=False).dropna(subset=['annotator_01', 'annotator_02', 'annotator_03', 'annotator_04', 'annotator_05']).reset_index(drop=True)
df = df_combined.drop(columns=['line_id', 'seg_id'])
df.index = df.index + 1

#### 라벨러마다 동의한 감정에 대한 빈도 및 분포 계산

In [6]:
# 감정 라벨 데이터를 리스트로 변환하는 함수
def labels_to_list(labels_str):
    if pd.isna(labels_str):
        return []
    return [label.strip() for label in labels_str.split(',')]

# 라벨 데이터를 리스트로 변환하여 새로 열을 추가
df['annotator_01_label_list'] = df['annotator_01'].apply(labels_to_list)
df['annotator_02_label_list'] = df['annotator_02'].apply(labels_to_list)
df['annotator_03_label_list'] = df['annotator_03'].apply(labels_to_list)
df['annotator_04_label_list'] = df['annotator_04'].apply(labels_to_list)
df['annotator_05_label_list'] = df['annotator_05'].apply(labels_to_list)

In [7]:
def statics_to_list(df):
    all_emotions = sum(df, [])

    # 감정 빈도 계산
    emotion_counts = pd.Series(all_emotions).value_counts()

    # 감정 분포 계산 (비율)
    emotion_distribution = emotion_counts / emotion_counts.sum()

    # 결과를 데이터프레임으로 정리
    emotion_stats = pd.DataFrame({
        '감정': emotion_counts.index,
        '빈도': emotion_counts.values,
        '분포(비율)': emotion_distribution.values
    })

    return emotion_stats

In [8]:
# 결과 출력
annotator01_statics = statics_to_list(df['annotator_01_label_list'])
annotator02_statics = statics_to_list(df['annotator_02_label_list'])
annotator03_statics = statics_to_list(df['annotator_03_label_list'])
annotator04_statics = statics_to_list(df['annotator_04_label_list'])
annotator05_statics = statics_to_list(df['annotator_05_label_list'])

In [9]:
def draw_graph_with_plotly(statics, title):
    """
    감정 분포를 그래프로 표현하는 함수 (Plotly 사용).
    
    Parameters:
        statics (DataFrame): '감정'과 '분포(비율)' 컬럼을 포함한 데이터프레임.
        title (str): 그래프 제목.
    """
    fig = px.bar(
        statics,
        x='감정',
        y='분포(비율)',
        color='감정',
        title=title,
        labels={'감정': '감정', '분포(비율)': '분포(비율)'},
        template='plotly_white'
    )
    fig.update_layout(
        xaxis=dict(tickangle=45),
        title=dict(font=dict(size=20)),
        xaxis_title="감정",
        yaxis_title="분포(비율)"
    )
    fig.show()

#### 모든 주석자의 감정 합산

In [10]:
# 각 주석자 통계 DF를 리스트로 준비
dfs = [
    annotator01_statics,
    annotator02_statics,
    annotator03_statics,
    annotator04_statics,
    annotator05_statics,
]

# 감정별 빈도 합산
total_statics = (
    pd.concat([df[['감정', '빈도']] for df in dfs], ignore_index=True)
      .assign(빈도=lambda x: pd.to_numeric(x['빈도'], errors='coerce').fillna(0))
      .groupby('감정', as_index=False)['빈도'].sum()
      .sort_values('빈도', ascending=False, ignore_index=True)
)

print(total_statics.head(10))

        감정     빈도
0    불안/걱정  10126
1       슬픔   8715
2      기대감   8399
3  안타까움/실망   8016
4      서러움   7423
5   신기함/관심   7094
6      비장함   6808
7     아껴주는   6786
8    감동/감탄   5316
9    당황/난처   5249

In [11]:
draw_graph_with_plotly(annotator01_statics, '이로 감정 분포')
print(annotator01_statics)
draw_graph_with_plotly(annotator02_statics, '해인 감정 분포')
print(annotator02_statics)
draw_graph_with_plotly(annotator03_statics, '슬 감정 분포')
print(annotator03_statics)
draw_graph_with_plotly(annotator04_statics, '송이 감정 분포')
print(annotator04_statics)
draw_graph_with_plotly(annotator05_statics, '종훈 감정 분포')
print(annotator05_statics)

             감정    빈도    분포(비율)
0         불안/걱정  2001  0.066182
1        신기함/관심  1847  0.061088
2           기대감  1828  0.060460
3          아껴주는  1615  0.053415
4           비장함  1504  0.049744
5           깨달음  1478  0.048884
6            슬픔  1412  0.046701
7       안타까움/실망  1373  0.045411
8           서러움  1294  0.042798
9         환영/호의  1173  0.038796
10           없음  1097  0.036282
11  흐뭇함(귀여움/예쁨)   968  0.032016
12       불쌍함/연민   925  0.030594
13        당황/난처   910  0.030098
14        감동/감탄   842  0.027849
15      부담/안_내킴   738  0.024409
16        힘듦/지침   729  0.024111
17        의심/불신   678  0.022424
18      패배/자기혐오   613  0.020275
19           놀람   607  0.020076
20       공포/무서움   559  0.018489
21         지긋지긋   472  0.015611
22           기쁨   441  0.014586
23        불평/불만   409  0.013527
24           존경   407  0.013461
25          고마움   400  0.013230
26           절망   389  0.012866
27          뿌듯함   341  0.011278
28       즐거움/신남   334  0.011047
29        편안/쾌적   312  0.010319
30          한심함   298  0.009856
31          죄책감   276  0.009128
32           짜증   271  0.008963
33        화남/분노   262  0.008665
34        안심/신뢰   252  0.008335
35      우쭐댐/무시함   225  0.007442
36           행복   195  0.006449
37           경악   192  0.006350
38        증오/혐오   179  0.005920
39         부끄러움   101  0.003340
40          귀찮음    92  0.003043
41         어이없음    87  0.002877
42     역겨움/징그러움    70  0.002315
43         재미없음    39  0.001290

             감정    빈도    분포(비율)
0           서러움  3580  0.091233
1         불안/걱정  3276  0.083486
2            슬픔  2480  0.063201
3       안타까움/실망  2248  0.057288
4          아껴주는  2240  0.057085
5           기대감  1871  0.047681
6        신기함/관심  1647  0.041972
7           비장함  1630  0.041539
8        불쌍함/연민  1265  0.032238
9         당황/난처  1067  0.027192
10        감동/감탄  1018  0.025943
11          깨달음  1008  0.025688
12        환영/호의   953  0.024286
13        힘듦/지침   943  0.024032
14  흐뭇함(귀여움/예쁨)   859  0.021891
15        불평/불만   826  0.021050
16           놀람   822  0.020948
17           기쁨   791  0.020158
18      부담/안_내킴   754  0.019215
19         지긋지긋   630  0.016055
20        의심/불신   615  0.015673
21      패배/자기혐오   614  0.015647
22       공포/무서움   551  0.014042
23           없음   551  0.014042
24          한심함   548  0.013965
25        안심/신뢰   525  0.013379
26           절망   506  0.012895
27           행복   502  0.012793
28          뿌듯함   490  0.012487
29        편안/쾌적   472  0.012029
30       즐거움/신남   451  0.011493
31           존경   450  0.011468
32           경악   399  0.010168
33          고마움   371  0.009455
34           짜증   346  0.008818
35        화남/분노   330  0.008410
36      우쭐댐/무시함   276  0.007034
37          귀찮음   275  0.007008
38         어이없음   255  0.006498
39          죄책감   229  0.005836
40        증오/혐오   206  0.005250
41         부끄러움   197  0.005020
42     역겨움/징그러움    90  0.002294
43         재미없음    83  0.002115

             감정    빈도    분포(비율)
0       안타까움/실망  2045  0.083757
1       부담/안_내킴  1910  0.078227
2           기대감  1838  0.075279
3         불안/걱정  1361  0.055742
4         당황/난처  1294  0.052998
5        불쌍함/연민  1214  0.049721
6        신기함/관심  1184  0.048493
7            슬픔  1160  0.047510
8            기쁨  1071  0.043865
9           서러움   960  0.039318
10          비장함   871  0.035673
11          깨달음   803  0.032888
12           놀람   775  0.031741
13           없음   775  0.031741
14         아껴주는   681  0.027892
15        감동/감탄   593  0.024287
16        힘듦/지침   574  0.023509
17        불평/불만   540  0.022117
18          뿌듯함   381  0.015605
19        의심/불신   363  0.014867
20  흐뭇함(귀여움/예쁨)   337  0.013802
21       공포/무서움   286  0.011714
22           절망   276  0.011304
23           존경   271  0.011099
24      패배/자기혐오   219  0.008970
25           행복   203  0.008314
26         부끄러움   194  0.007946
27       즐거움/신남   188  0.007700
28        안심/신뢰   180  0.007372
29          한심함   178  0.007290
30        환영/호의   177  0.007249
31        증오/혐오   172  0.007045
32        편안/쾌적   171  0.007004
33         지긋지긋   170  0.006963
34           경악   161  0.006594
35           짜증   132  0.005406
36        화남/분노   128  0.005242
37          고마움   118  0.004833
38         어이없음   114  0.004669
39      우쭐댐/무시함   114  0.004669
40     역겨움/징그러움   104  0.004260
41          귀찮음    64  0.002621
42         재미없음    43  0.001761
43          죄책감    23  0.000942

             감정    빈도    분포(비율)
0            슬픔  2880  0.101305
1         힘듦/지침  2251  0.079180
2         불안/걱정  2180  0.076682
3           비장함  1661  0.058426
4           기대감  1298  0.045658
5         감동/감탄  1297  0.045622
6       안타까움/실망  1276  0.044884
7            절망  1239  0.043582
8          아껴주는  1231  0.043301
9            기쁨  1212  0.042633
10           행복  1153  0.040557
11        당황/난처   787  0.027683
12          서러움   773  0.027191
13       불쌍함/연민   738  0.025959
14       신기함/관심   645  0.022688
15        불평/불만   641  0.022547
16          깨달음   570  0.020050
17        환영/호의   567  0.019944
18        편안/쾌적   547  0.019241
19           경악   526  0.018502
20      부담/안_내킴   525  0.018467
21       즐거움/신남   465  0.016357
22        의심/불신   400  0.014070
23  흐뭇함(귀여움/예쁨)   378  0.013296
24       공포/무서움   369  0.012980
25           놀람   358  0.012593
26        화남/분노   356  0.012522
27        안심/신뢰   353  0.012417
28        증오/혐오   298  0.010482
29           존경   258  0.009075
30         재미없음   227  0.007985
31      패배/자기혐오   221  0.007774
32          한심함   152  0.005347
33         부끄러움   119  0.004186
34         지긋지긋   114  0.004010
35          뿌듯함   110  0.003869
36           없음    92  0.003236
37         어이없음    58  0.002040
38     역겨움/징그러움    39  0.001372
39          죄책감    37  0.001301
40           짜증    13  0.000457
41          고마움     7  0.000246
42      우쭐댐/무시함     4  0.000141
43          귀찮음     4  0.000141

             감정    빈도    분포(비율)
0        신기함/관심  1771  0.071187
1         감동/감탄  1566  0.062947
2           기대감  1564  0.062867
3         불안/걱정  1308  0.052577
4           깨달음  1292  0.051933
5            놀람  1232  0.049522
6         당황/난처  1191  0.047874
7           비장함  1142  0.045904
8       안타까움/실망  1074  0.043171
9          아껴주는  1019  0.040960
10          서러움   816  0.032800
11           슬픔   783  0.031474
12       불쌍함/연민   751  0.030187
13  흐뭇함(귀여움/예쁨)   747  0.030027
14           기쁨   654  0.026288
15        힘듦/지침   552  0.022188
16        의심/불신   528  0.021224
17        불평/불만   474  0.019053
18           절망   458  0.018410
19        편안/쾌적   445  0.017887
20      부담/안_내킴   431  0.017325
21           존경   408  0.016400
22       공포/무서움   398  0.015998
23      패배/자기혐오   395  0.015877
24          고마움   358  0.014390
25           행복   337  0.013546
26           경악   322  0.012943
27        안심/신뢰   311  0.012501
28          뿌듯함   248  0.009969
29         지긋지긋   229  0.009205
30          한심함   221  0.008883
31        증오/혐오   220  0.008843
32        환영/호의   220  0.008843
33           짜증   211  0.008481
34         어이없음   192  0.007718
35       즐거움/신남   179  0.007195
36         재미없음   163  0.006552
37        화남/분노   143  0.005748
38          죄책감   141  0.005668
39         부끄러움   126  0.005065
40     역겨움/징그러움    85  0.003417
41           없음    67  0.002693
42      우쭐댐/무시함    66  0.002653
43          귀찮음    40  0.001608

### 여러 행에 대해 각 주석자 감정의 "분포(비율)"를 계산한 다음, 감정 별 총합하여 최종 분포

In [12]:
from collections import defaultdict

class EmotionDistributionCalculator:
    def __init__(self, df, annotator_columns): # 초기설정
        self.df = df
        self.annotator_columns = annotator_columns

    def calculate_row_emotion_distribution(self, emotion_list): 
        """
        한 행의 감정 리스트를 받아 감정 분포를 계산
        :param emotion_list: ['기쁨', '슬픔', '기쁨'] 등과 같은 감정 라벨 리스트
        :return: 감정:비율의 딕셔너리 (예: {'기쁨': 0.67, '슬픔': 0.33})
        """
        if not emotion_list: # 빈 리스트면 빈 딕셔너리 반환
            return {} 
        
        total = len(emotion_list)  # 총 감정 개수
        counts = pd.Series(emotion_list).value_counts()  # 감정별 등장 횟수 세기
        distribution = counts / total  # 감정별 비율 계산
        return distribution.to_dict() # 딕셔너리 형태로 반환

    def calculate_annotator_distribution(self, annotator):
        """
        특정 주석자에 대한 전체 감정 분포를 계산
        :param annotator: 주석자 컬럼명 (예: 'annotator01')
        :return: 해당 주석자의 감정 분포를 담은 DataFrame
        """
        total_distribution = defaultdict(float)  # 감정별 누적 분포를 저장할 딕셔너리

        # 모든 행(텍스트)에 대해 반복
        for i in range(len(self.df)):
            row_dist = self.calculate_row_emotion_distribution(self.df[annotator].iloc[i]) # 각 행의 감정 비율 계산
            for emotion, value in row_dist.items():
                total_distribution[emotion] += value # 감정별 분포를 누적합

         # 딕셔너리를 DataFrame으로 변환
        annotator_df = pd.DataFrame(list(total_distribution.items()), columns=['감정', '총합 분포(비율)'])
        annotator_df = annotator_df.sort_values(by='총합 분포(비율)', ascending=False).reset_index(drop=True) # 분포 기준으로 내림차순 정렬

        # 백분율로 환산
        annotator_df = self.convert_to_percentage(annotator_df)

        # 주석자 이름 컬럼 추가
        annotator_df['주석자'] = annotator

        return annotator_df

    def convert_to_percentage(self, distribution_df):
        """
        감정 분포를 백분율로 변환
        :param distribution_df: '총합 분포(비율)' 컬럼이 포함된 DataFrame
        :return: '백분율(%)' 컬럼이 추가된 DataFrame
        """
        total_sum = distribution_df['총합 분포(비율)'].sum() # 전체 합
        distribution_df['백분율(%)'] = (distribution_df['총합 분포(비율)'] / total_sum) * 100  # 백분율 계산
        
        return distribution_df

    def calculate_all_distributions(self):
        """
        모든 주석자에 대한 감정 분포를 계산하여 하나의 DataFrame으로 통합
        :return: 모든 주석자의 감정 분포가 포함된 통합 DataFrame
        """
        all_distributions = []

        for annotator in self.annotator_columns:
            annotator_df = self.calculate_annotator_distribution(annotator) # 각 주석자별 감정 분포 계산
            all_distributions.append(annotator_df)

        # 여러 주석자의 결과를 하나의 DataFrame으로 결합
        final_df = pd.concat(all_distributions, ignore_index=True)
        return final_df

In [13]:
# 주석자 컬럼명을 리스트로 정의
# 각 컬럼은 이미 감정 라벨 리스트로 전처리된 상태여야 함
annotator_columns = ['annotator_01_label_list', 'annotator_02_label_list', 'annotator_03_label_list', 'annotator_04_label_list', 'annotator_05_label_list']

# 감정 분포 계산 클래스의 인스턴스를 생성
# 입력: 전체 데이터프레임과 주석자 컬럼 목록
calculator = EmotionDistributionCalculator(df, annotator_columns)

# 모든 주석자의 감정 분포를 계산하여 하나의 통합 DataFrame 생성
final_df = calculator.calculate_all_distributions()

In [14]:
final_df

           감정   총합 분포(비율)    백분율(%)                      주석자
0      신기함/관심  601.559524  7.892410  annotator_01_label_list
1          없음  583.378571  7.653878  annotator_01_label_list
2         기대감  504.352778  6.617066  annotator_01_label_list
3       불안/걱정  491.807287  6.452470  annotator_01_label_list
4         비장함  431.571068  5.662176  annotator_01_label_list
..        ...         ...       ...                      ...
215      부끄러움   36.779762  0.482547  annotator_05_label_list
216     화남/분노   36.426984  0.477919  annotator_05_label_list
217   우쭐댐/무시함   25.283333  0.331715  annotator_05_label_list
218  역겨움/징그러움   20.422619  0.267943  annotator_05_label_list
219       귀찮음   11.635714  0.152660  annotator_05_label_list

[220 rows x 4 columns]

In [15]:
def split_final_df_by_annotator(final_df):
    segmented_dfs = {} # 주석자별 DataFrame을 저장할 딕셔너리 생성
    unique_annotators = final_df['주석자'].unique()  # '주석자' 열에서 고유 주석자 목록 추출

    for annotator in unique_annotators:
        # 해당 주석자의 행만 필터링하고, 인덱스를 초기화하여 새로운 DataFrame 생성
        segmented_dfs[annotator] = final_df[final_df['주석자'] == annotator].reset_index(drop=True)

    return segmented_dfs # 주석자별로 나눈 DataFrame 딕셔너리 반환

In [16]:
segmented_dfs = split_final_df_by_annotator(final_df)

In [17]:
# 프레임 잘라서 따로 변수로 보관
annotator01_df = segmented_dfs['annotator_01_label_list']
annotator02_df = segmented_dfs['annotator_02_label_list']
annotator03_df = segmented_dfs['annotator_03_label_list']
annotator04_df = segmented_dfs['annotator_04_label_list']
annotator05_df = segmented_dfs['annotator_05_label_list']

In [18]:
annotator01_df

             감정   총합 분포(비율)    백분율(%)                      주석자
0        신기함/관심  601.559524  7.892410  annotator_01_label_list
1            없음  583.378571  7.653878  annotator_01_label_list
2           기대감  504.352778  6.617066  annotator_01_label_list
3         불안/걱정  491.807287  6.452470  annotator_01_label_list
4           비장함  431.571068  5.662176  annotator_01_label_list
5          아껴주는  402.817100  5.284927  annotator_01_label_list
6            슬픔  347.788961  4.562962  annotator_01_label_list
7           깨달음  344.525036  4.520140  annotator_01_label_list
8       안타까움/실망  321.490115  4.217923  annotator_01_label_list
9           서러움  281.734668  3.696335  annotator_01_label_list
10        환영/호의  269.732576  3.538869  annotator_01_label_list
11  흐뭇함(귀여움/예쁨)  253.930195  3.331543  annotator_01_label_list
12       불쌍함/연민  216.103571  2.835261  annotator_01_label_list
13        당황/난처  206.327128  2.706995  annotator_01_label_list
14        감동/감탄  187.129762  2.455127  annotator_01_label_list
15      부담/안_내킴  159.870346  2.097486  annotator_01_label_list
16        의심/불신  158.240584  2.076103  annotator_01_label_list
17           놀람  150.547619  1.975172  annotator_01_label_list
18        힘듦/지침  149.365584  1.959664  annotator_01_label_list
19       공포/무서움  124.554401  1.634143  annotator_01_label_list
20      패배/자기혐오  113.011616  1.482703  annotator_01_label_list
21         지긋지긋  100.068687  1.312893  annotator_01_label_list
22        편안/쾌적   92.676190  1.215904  annotator_01_label_list
23           기쁨   92.156385  1.209084  annotator_01_label_list
24       즐거움/신남   88.761905  1.164549  annotator_01_label_list
25           존경   86.617857  1.136419  annotator_01_label_list
26        불평/불만   80.881746  1.061162  annotator_01_label_list
27          고마움   76.526623  1.004023  annotator_01_label_list
28           절망   75.687338  0.993012  annotator_01_label_list
29          뿌듯함   74.125000  0.972514  annotator_01_label_list
30          한심함   64.822330  0.850464  annotator_01_label_list
31        안심/신뢰   60.641270  0.795608  annotator_01_label_list
32        화남/분노   57.042929  0.748398  annotator_01_label_list
33      우쭐댐/무시함   56.169841  0.736944  annotator_01_label_list
34           짜증   55.638889  0.729978  annotator_01_label_list
35          죄책감   52.454040  0.688193  annotator_01_label_list
36           경악   38.274603  0.502160  annotator_01_label_list
37           행복   37.195635  0.488004  annotator_01_label_list
38        증오/혐오   36.881349  0.483880  annotator_01_label_list
39         부끄러움   26.655556  0.349719  annotator_01_label_list
40          귀찮음   23.176587  0.304075  annotator_01_label_list
41         어이없음   19.371429  0.254152  annotator_01_label_list
42     역겨움/징그러움   13.726984  0.180097  annotator_01_label_list
43         재미없음   12.608333  0.165420  annotator_01_label_list

In [19]:
def plot_full_emotion_distribution(df, value_col='백분율(%)', title='KPoEM 전체 감정 백분율 분포'):
    """
    44가지 감정의 백분율 분포를 plotly로 가로 막대 그래프로 시각화 (얇은 막대 포함)

    Parameters:
    - df: '감정'과 백분율 컬럼을 포함한 DataFrame
    - value_col: 시각화 기준이 되는 값 (기본값: '백분율(%)')
    - title: 그래프 제목
    """
    df_sorted = df.sort_values(by=value_col, ascending=True) # 감정별 비율을 기준으로 오름차순 정렬

    fig = px.bar(
        df_sorted,
        x=value_col, # 백분율(%) 기준으로 정렬
        y='감정', # 감정 기준으로 정렬
        orientation='h', # 가로 막대 그래프
        text=df_sorted[value_col].round(2), # 소수점 2자리로 반올림
        title=title
    )

    fig.update_layout(
        xaxis_title=value_col,
        yaxis_title='감정',
        template='plotly_white',
        height=44 * 17,  # 감정 1개당 높이 20px 정도로 조정 → 880px
        margin=dict(l=100, r=30, t=60, b=30)
    )

    fig.update_traces(marker=dict(line=dict(width=0.5, color='gray')), textposition='outside')

    fig.show()

In [20]:
plot_full_emotion_distribution(annotator01_df, value_col='백분율(%)', title='이로 감정 분포 시각화')
plot_full_emotion_distribution(annotator02_df, value_col='백분율(%)', title='해인 감정 분포 시각화')
plot_full_emotion_distribution(annotator03_df, value_col='백분율(%)', title='슬 감정 분포 시각화')
plot_full_emotion_distribution(annotator04_df, value_col='백분율(%)', title='송이 감정 분포 시각화')
plot_full_emotion_distribution(annotator05_df, value_col='백분율(%)', title='종훈 감정 분포 시각화')

#### 5명중 3명 이상이 동의한 감정에 대한 빈도 및 분포 계산

In [21]:
def get_labels_agreed_by_at_least_k(row, k=3):
    """
    각 행(row)에 대해, 최소 k명 이상이 동의한 감정만 추출

    Parameters:
    - row: annotator label list들이 있는 DataFrame row
    - k: 동의한 annotator 최소 수 (기본 2명)

    Returns:
    - 감정 리스트 중 k명 이상이 공통으로 선택한 감정 리스트
    """
    all_labels = (
        row['annotator_01_label_list'] +
        row['annotator_02_label_list'] +
        row['annotator_03_label_list'] +
        row['annotator_04_label_list'] +
        row['annotator_05_label_list']
    )
    counter = pd.Series(all_labels).value_counts() # 감정별 개수 세기
    return [label for label, count in counter.items() if count >= k] # k명 이상이 동의한 감정 리스트

In [22]:
# 3명 이상 동의한 감정 리스트로 새 컬럼 생성
df['common_labels'] = df.apply(lambda row: get_labels_agreed_by_at_least_k(row, k=3), axis=1)

df[['common_labels']].head(10) # 3명 이상 동의한 감정 리스트 확인

               common_labels
1                      [비장함]
2                [비장함, 부끄러움]
3                      [기대감]
4   [패배/자기혐오, 절망, 슬픔, 힘듦/지침]
5            [기쁨, 기대감, 아껴주는]
6        [비장함, 불쌍함/연민, 아껴주는]
7                         []
8                      [비장함]
9               [기대감, 감동/감탄]
10                      [슬픔]

In [23]:
# 5명 전부 동의한 감정 리스트로 새 컬럼 생성
df['common_labels_5'] = df.apply(lambda row: get_labels_agreed_by_at_least_k(row, k=5), axis=1)

df[['common_labels_5']].head(10) # 3명 이상 동의한 감정 리스트 확인

   common_labels_5
1            [비장함]
2            [비장함]
3               []
4        [패배/자기혐오]
5             [기쁨]
6            [비장함]
7               []
8               []
9               []
10              []

#### 공통라벨이 없는 행 개수 출력

In [24]:
# 예: 'my_column'에 리스트 데이터가 들어 있는 경우
empty_list_count = df['common_labels'].apply(lambda x: isinstance(x, list) and len(x) == 0).sum()

print(f"빈 리스트([])인 행의 개수: {empty_list_count}")

빈 리스트([])인 행의 개수: 570

In [25]:
# 공통 라벨링 csv반환

selected_columns = df[['poem_id', 'text', 'sub_title', 'title', 'poet', 'common_labels']]
selected_columns.to_csv('../data/edited_columns.tsv', index=False)

In [34]:
# 해당 감정 분포 계산
at_least_agreed_statics = statics_to_list(df['common_labels'])

# 시각화 (이미 정의된 함수 사용)
draw_graph_with_plotly(at_least_agreed_statics, '3명 이상 일치 감정 분포')

# 확인
print(at_least_agreed_statics)

             감정    빈도    분포(비율)
0         불안/걱정  1487  0.085215
1           기대감  1332  0.076332
2            슬픔  1307  0.074900
3       안타까움/실망  1241  0.071117
4          아껴주는  1071  0.061375
5        신기함/관심  1069  0.061261
6           비장함  1047  0.060000
7           서러움   886  0.050774
8         감동/감탄   695  0.039828
9        불쌍함/연민   608  0.034842
10          깨달음   601  0.034441
11        당황/난처   566  0.032436
12           기쁨   539  0.030888
13        힘듦/지침   480  0.027507
14  흐뭇함(귀여움/예쁨)   419  0.024011
15           놀람   354  0.020287
16      부담/안_내킴   332  0.019026
17       공포/무서움   278  0.015931
18           없음   265  0.015186
19        의심/불신   265  0.015186
20           절망   247  0.014155
21        불평/불만   241  0.013811
22           행복   194  0.011117
23      패배/자기혐오   188  0.010774
24           존경   186  0.010659
25        편안/쾌적   186  0.010659
26        환영/호의   178  0.010201
27       즐거움/신남   135  0.007736
28        증오/혐오   115  0.006590
29           경악   114  0.006533
30          한심함   108  0.006189
31          뿌듯함   101  0.005788
32        화남/분노    98  0.005616
33          고마움    93  0.005330
34        안심/신뢰    84  0.004814
35         지긋지긋    66  0.003782
36         부끄러움    61  0.003496
37           짜증    57  0.003266
38      우쭐댐/무시함    44  0.002521
39     역겨움/징그러움    34  0.001948
40          죄책감    29  0.001662
41         어이없음    27  0.001547
42         재미없음    14  0.000802
43          귀찮음     8  0.000458

In [27]:
# 해당 감정 분포 계산
at_least_agreed_statics = statics_to_list(df['common_labels_5'])

# 시각화 (이미 정의된 함수 사용)
draw_graph_with_plotly(at_least_agreed_statics, '5명 일치 감정 분포')

# 확인
print(at_least_agreed_statics)

             감정   빈도    분포(비율)
0            슬픔  263  0.134115
1           기대감  195  0.099439
2           비장함  183  0.093320
3           서러움  127  0.064763
4       안타까움/실망  127  0.064763
5          아껴주는  125  0.063743
6         불안/걱정  125  0.063743
7           깨달음   89  0.045385
8        불쌍함/연민   88  0.044875
9         감동/감탄   78  0.039776
10       신기함/관심   74  0.037736
11           기쁨   72  0.036716
12       공포/무서움   47  0.023967
13        당황/난처   43  0.021928
14  흐뭇함(귀여움/예쁨)   41  0.020908
15        힘듦/지침   38  0.019378
16           놀람   37  0.018868
17        증오/혐오   19  0.009689
18      부담/안_내킴   18  0.009179
19      패배/자기혐오   18  0.009179
20         부끄러움   17  0.008669
21        편안/쾌적   17  0.008669
22        화남/분노   17  0.008669
23           절망   16  0.008159
24       즐거움/신남   14  0.007139
25        불평/불만   12  0.006119
26        의심/불신   12  0.006119
27           행복   11  0.005609
28           존경   11  0.005609
29           없음    7  0.003570
30          뿌듯함    4  0.002040
31     역겨움/징그러움    3  0.001530
32           경악    3  0.001530
33        환영/호의    3  0.001530
34          한심함    2  0.001020
35        안심/신뢰    2  0.001020
36          죄책감    2  0.001020
37           짜증    1  0.000510

In [28]:
# CSV로 저장
df.to_csv("../data/data_analyicts_1216.csv", index=False, encoding="utf-8-sig")

### 참고. KOTE Guideline 4.3. Data Description (6page)

#### Agreement (데이터 당 감정별 동의한 주석자 단위 통계)

In [29]:
from collections import Counter

def calculate_agreement_levels(df, k_range=[1, 2, 3, 4, 5]):
    agreement_counts = {k: 0 for k in k_range} # k_range에 있는 각 k에 대해 동의자 수를 카운트하기 위한 딕셔너리

    for idx, row in df.iterrows(): # iterrows()를 사용하여 각 행을 반복
        all_labels = (
            row['annotator_01_label_list'] +
            row['annotator_02_label_list'] +
            row['annotator_03_label_list'] +
            row['annotator_04_label_list'] +
            row['annotator_05_label_list']
        )
        label_counter = Counter(all_labels) # 각 라벨의 개수를 세기 위한 Counter 객체 생성
        max_label_agreement = max(label_counter.values()) if label_counter else 0
        # max_label_agreement는 각 행에서 가장 많이 나타나는 라벨의 개수 (최대값을)

        for k in k_range:
            if max_label_agreement >= k: 
                agreement_counts[k] += 1 #해당 딕셔너리의 k에 대해 동의자 수를 증가시킴

    # 비율 계산
    total = len(df)
    agreement_stats = pd.DataFrame({
        '최소 동의자 수': list(agreement_counts.keys()),
        '텍스트 수': list(agreement_counts.values()),
        '전체 대비 비율 (%)': [round(v / total * 100, 2) for v in agreement_counts.values()]
    })

    return agreement_stats

In [30]:
agreement_df = calculate_agreement_levels(df) 
print(agreement_df) #KOTE / x=1 : 50,000 (100%) / x=2:

   최소 동의자 수  텍스트 수  전체 대비 비율 (%)
0         1   7622        100.00
1         2   7613         99.88
2         3   7052         92.52
3         4   4659         61.13
4         5   1725         22.63

#### texts labeled for NO EMOTION (주석자 별 '없음'에 라벨링한 데이터 수)

In [31]:
# 라벨 컬럼
label_cols = ['annotator_01', 'annotator_02', 'annotator_03', 'annotator_04', 'annotator_05']

# # 각 annotator 라벨 컬럼을 리스트로 변환
# for col in label_cols:
#     df[f'{col}_label_list'] = df[col].apply(labels_to_list)

In [32]:
# 각 행에서 '없음'을 라벨링한 주석자 수 계산
def count_none_label(row, target='없음'):
    return sum(target in row[f'{col}_label_list'] for col in label_cols)

df['none_label_count'] = df.apply(count_none_label, axis=1)

# 없음 라벨 주석자 수에 따른 분포 집계
none_label_distribution = df['none_label_count'].value_counts().sort_index()
none_label_table = pd.DataFrame({
    '없음 라벨 주석자 수': none_label_distribution.index,
    '텍스트 수': none_label_distribution.values
})

none_label_table['전체 대비 비율 (%)'] = round(none_label_table['텍스트 수'] / len(df) * 100, 2)

In [33]:
none_label_table
#예시 샘플들을 넣어줘야함. 5인이 모두 '없음'을 표시한 특징데이터, 
# '없음'이 특징적일 수 있는 인사이트가 아닌지 고민해볼것.

   없음 라벨 주석자 수  텍스트 수  전체 대비 비율 (%)
0            0   6047         79.34
1            1    897         11.77
2            2    413          5.42
3            3    208          2.73
4            4     50          0.66
5            5      7          0.09